package br.com.grupo5.Quality.database.enums;

public enum PermissaoPlano {
    VISUALIZAR,
    EDITAR,
    CONCLUIR,
    EXCLUIR,
    GERENCIAR_PARTICIPANTES,
    GERENCIAR_DOCUMENTOS,
    GERENCIAR_ARTEFATOS,
    GERENCIAR_CHECKLISTS,
    AUDITAR,
    ESCALONAR_NAO_CONFORMIDADE,
    GERENCIAR_ESCALONAMENTOS,
    TRATAR_NAO_CONFORMIDADE
}
