package br.com.grupo5.Quality.database.enums;

public enum TipoNotificacao {
    NAO_CONFORMIDADE_ENCAMINHADA_EQUIPE,
    NAO_CONFORMIDADE_ATRIBUIDA,
    PRAZO_NAO_CONFORMIDADE_VENCIDO,
    NAO_CONFORMIDADE_ESCALONADA_N1,
    PRAZO_ESCALONAMENTO_N1_VENCIDO,
    NAO_CONFORMIDADE_ESCALONADA_N2,
    PRAZO_ESCALONAMENTO_N2_VENCIDO,
    ALERTA_SUPERIOR_EQUIPE_RESOLUCAO,
    RESOLUCAO_INFORMADA,
    AJUSTES_RESOLUCAO_SOLICITADOS
}
