package br.com.grupo5.Quality.database.enums;

public enum TipoEventoNaoConformidade {
    NAO_CONFORMIDADE_IDENTIFICADA,
    ENCAMINHAMENTO_EQUIPE,
    COMUNICACAO_ENVIADA,
    COMUNICACAO_FALHOU,
    RESOLUCAO_INFORMADA,
    RESOLUCAO_APROVADA,
    AJUSTES_SOLICITADOS,
    ESCALONAMENTO_N1,
    ESCALONAMENTO_N2,
    NOTIFICACAO_GERADA
}
